title: COMSM0067
description: COMSM0067 Advanced Topics in Programming Languages
code: COMSM0067
name: Advanced Topics in Programming Languages
year: 2021/22
banner:
  url: Images/banner.png
  desc: A banner for the unit in the colours of Norton Commander